import type { Metadata } from 'next';
import cn from '~/utils/cn';
import './globals.css';
import fonts from '~/configs/fonts';

export const metadata: Metadata = {
  title: 'Hong Van',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          fonts.sans.className,
          'min-h-screen bg-gray-800 text-white font-light',
        )}
      >
        {children}
      </body>
    </html>
  );
}
